### ISSUE TITLE
Integer verbosity levels are not handled

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#27]
Usage docs suggest verbosity can be set either with integers or strings but integers don't work:

```
  --verbosity VERBOSITY
                        Relative measure of interest in logs; this can be an
                        integer in [0, 5], or a Python builtin logging name)
```

```
 python ~/code/pepatac/tools/bamSitesToWig.py  --verbosity 5

Traceback (most recent call last):
  File "/home/ns5bc/code/pepatac/tools/bamSitesToWig.py", line 286, in <module>
    _LOGGER = logger_via_cli(args)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pararead/logs.py", line 121, in logger_via_cli
    return setup_logger(**logs_cli_args)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pararead/logs.py", line 199, in setup_logger
    level = _level_from_verbosity(verbosity or LOGGING_LEVEL)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pararead/logs.py", line 326, in _level_from_verbosity
    "{}".format(verbosity, ", ".join(LEVEL_BY_VERBOSITY)))
ValueError: Invalid logging verbosity ('5'); choose from: CRITICAL, ERROR, WARN, INFO, DEBUG
```

**Comment by nsheff** [comment]
Sorry I messed up with the merges, inadvertently merged into master...d'oh!
