### ISSUE TITLE
python3 comaptibility issue

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#32]
```

> `tools/bamQC.py -i /home/ns5bc/pepatac_test/test1/aligned_hg38/test1_sort.bam -c 1 -o /home/ns5bc/pepatac_test/test1/QC_hg38/test1_bamQC.tsv` (7490)

<pre>
Traceback (most recent call last):
  File "tools/bamQC.py", line 15, in <module>
    import pararead
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/__init__.py", line 2, in <module>
    from .processor import ParaReadProcessor
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/processor.py", line 644
    enumerate(readsfile), key=lambda (i, _): int(i / chunksize))
                                     ^
SyntaxError: invalid syntax

```

discovered while running pepatac test sample.

**Comment by nsheff** [comment]
can be reproduced with internal example in this repo:

```
python count_reads.py ~/13269.spikein.aln.deduplicated.bam  -O ~/test.txt
Traceback (most recent call last):
  File "count_reads.py", line 7, in <module>
    from pararead import ParaReadProcessor
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/__init__.py", line 2, in <module>
    from .processor import ParaReadProcessor
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/processor.py", line 644
    enumerate(readsfile), key=lambda (i, _): int(i / chunksize))
                                     ^
```
