### ISSUE TITLE
python3: no module named _version

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#36]
```
python count_reads.py ~/13269.spikein.aln.deduplicated.bam  -O ~/test.txt
Traceback (most recent call last):
  File "count_reads.py", line 7, in <module>
    from pararead import ParaReadProcessor
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/__init__.py", line 2, in <module>
    from .processor import ParaReadProcessor
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/processor.py", line 24, in <module>
    from .logs import setup_logger
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/logs.py", line 7, in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'
```

**Comment by nsheff** [comment]
dang you beat me to it.
