### ISSUE TITLE
Mismatched type comparison in log setup

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#37]
```

<pre>
Traceback (most recent call last):
  File "tools/bamQC.py", line 242, in <module>
    _LOGGER = logger_via_cli(args)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/logs.py", line 121, in logger_via_cli
    return setup_logger(**logs_cli_args)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pararead/logs.py", line 233, in setup_logger
    level <= logging.DEBUG
TypeError: '<=' not supported between instances of 'str' and 'int'
</pre>

```

Maybe you should make your own logger package and wrap all this stuff up, since it seems like it's in lots of packages

**Comment by vreuter** [comment]
Glad Python 3 forbids those comparisons; it's insane that they've been permitted.
