### ISSUE TITLE
Cannot remove tutorial key from docs conf

### ISSUE THREAD

**Issue by vreuter** [databio/pararead#38]
With line
```
    - Tutorial: tutorial.md
```
removed from the docs conf, this happens:

```
Traceback (most recent call last):
  File "/home/vpr9v/venvs/py2/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 267, in build
    nav = get_navigation(files, config)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/structure/nav.py", line 104, in get_navigation
    items = _data_to_navigation(nav_config, files, config)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/structure/nav.py", line 162, in _data_to_navigation
    for item in data
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/structure/nav.py", line 155, in _data_to_navigation
    for key, value in data.items()
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/structure/nav.py", line 165, in _data_to_navigation
    file = files.get_file_from_path(path)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/mkdocs/structure/files.py", line 33, in get_file_from_path
    return self.src_paths.get(os.path.normpath(path))
  File "/home/vpr9v/venvs/py2/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by nsheff** [comment]
if you remove that line the yaml is no longer correct format because you have an opening section "User guides:" ending with a colon but no entries... so this is the expected behavior from mkdocs

**Comment by nsheff** [comment]
you can solve by removing the whole user guides section

**Comment by vreuter** [comment]
:ok_hand:  got it
