### ISSUE TITLE
limit argument is broken

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#41]
```
Configured logger 'root' using pararead v0.6
Traceback (most recent call last):
  File "src/bamSitesToWig.py", line 467, in <module>
    verbosity=args.verbosity)
  File "src/bamSitesToWig.py", line 63, in __init__
    retain_temp=retain_temp)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pararead/processor.py", line 132, in __init__
    prefix=prefix, dir=temp_folder_parent_path)
  File "/usr/lib/python3.5/tempfile.py", line 505, in mkdtemp
    file = _os.path.join(dir, prefix + name + suffix)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
```

when passing a `--limit` to bamSitesToWig it crashes.

**Comment by nsheff** [comment]
appears to be that the constructor signature to pararead changed. I've adapted that script.
