### ISSUE TITLE
error installing pararead

### ISSUE THREAD

**Issue by mbassalbioinformatics** [databio/pararead#45]
Hi Im trying to install pararead 0.7.0 and it errors out with the following 

```
Processing ./pararead-0.7.0.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      /home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      /home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running egg_info
      creating /tmp/pip-pip-egg-info-u89_tst7/pararead.egg-info
      writing /tmp/pip-pip-egg-info-u89_tst7/pararead.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-u89_tst7/pararead.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-u89_tst7/pararead.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-u89_tst7/pararead.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-u89_tst7/pararead.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-u89_tst7/pararead.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-35k8icim/setup.py", line 45, in <module>
          setup(
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 545, in run
          self.prune_file_list()
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/command/sdist.py", line 161, in prune_file_list
          super().prune_file_list()
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/mbassal/anaconda3/envs/pepatac/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

any ideas how to rectify this and get it working?

**Comment by khoroshevskyi** [comment]
After looking more closely into this issue with @donaldcampbelljr, it seems that the issue is caused by setuptools.
Many users have encountered this error: https://github.com/pypa/setuptools/issues/4483
Try manually upgrading setuptools or downgrading it to version 70.x.

Additionally, we are going to release a new version of `pararead` and update the supported Python version.

Let us know if this solves your issue.

**Comment by mbassalbioinformatics** [comment]
yep seems to be fixed now, thanks!!
